Feature/create bot
Studio-Yandex-Practicum/dementia_bot pull request #3
Opened 2023-09-08 18:55 UTC by Aleksandr140590

Основа бота. Хэндлер на команду start пока находится в мэйн. Докерфайл.

2023-09-08 19:14 UTC, nikitapatrakov requested changes

2023-09-08 19:14 UTC, nikitapatrakov commented on bot/core/config.py
> +dp = Dispatcher()
Предлагаю загрузку данных сделать через Pydantic https://docs.pydantic.dev/latest/usage/pydantic_settings/
образец:
class Settings(BaseSettings):
    telegram_api_token: str = None
    
settings = Settings()

2023-09-08 19:14 UTC, nikitapatrakov commented on bot/main.py
> +    asyncio.run(main())
В этом файле у нас должен запускаться только бот 
def start():
    """Запуск бота."""
    if settings.webhook_mode:
        run_webhooks()
    else:
        run_polling()


if __name__ == "__main__":
    start()

2023-09-08 19:14 UTC, nikitapatrakov commented on bot/bot/__init__.py
Вот в этой папке рекомендую создать файл с настройками бота. Бот должен поддерживать работу как pooling и webhooks. В зависимости от настроек. 
WEBHOOK_MODE=False

2023-09-09 16:00 UTC, Aleksandr140590 commented
Обновил согласно рекомендациям

2023-09-09 17:11 UTC, Aleksandr140590 commented on bot/bot/__init__.py
добавил запуск poling & webhook в зависимости от настроек.

2023-09-09 17:12 UTC, Aleksandr140590 commented on bot/core/config.py
> +dp = Dispatcher()
Добавлены настройки с использованием pydantic_settings

2023-09-11 09:28 UTC, nikitapatrakov commented on bot/bot/__init__.py
По коду все хорошо, но я думаю лучше стоить оформить образец файла .env.example. И сделать файл README по запуску бота.

2023-09-11 09:28 UTC, nikitapatrakov commented
По коду все хорошо, но я думаю лучше стоить оформить образец файла .env.example. И сделать файл README по запуску бота.

2023-09-11 16:15 UTC, Aleksandr140590 commented
Добавлен README & env.example

2023-09-11 16:46 UTC, merged