Add Swagger /Fix bug
Studio-Yandex-Practicum/dementia_bot pull request #61
Opened 2024-01-18 17:44 UTC by maxer1977

1.  Swagger (основная задача)
Установлена библиотека drf-yasg (зависимости автоматически внесены в poetry.lock)
Подключение Swagger осуществлено в url и settings

2. Найдена ошибка в expert-system/appbot/views.py - при выполнении запроса get_result(request, telegram_id) с несуществующим ID программа падала на строке "except TestResultParticipantSerializer.DoesNotExist:" - у объекта нет атрибута DoesNotExist - заменил "except TestParticipant.DoesNotExist:"

2024-01-21 17:11 UTC, nikitapatrakov commented
Все отлично, а есть возможность добавить примеры запросов как на FastApi в теории выполняли ???

2024-01-21 17:12 UTC, nikitapatrakov requested changes
Попробовать описать примеры в запросах

2024-01-23 16:37 UTC, maxer1977 commented
Добавил примеры в запросы - примеры отображаются на странице swagger/redoc
Запросы работают за исключением def submit_test(request) api/submit/ - точнее он не отрабатывает до конца и сваливается в ошибку, так как в нем есть обращение методам из utils.py, которые работают с ранее данными ответами (а их в этом случае нет...). Если есть замечания - готов оперативно отработать.

И заметил следующие моменты:
get_result - если пользователь проходит несколько тестов (2 и более записи в TestParticipant) -> ошибка 500
Пользователь может несколько раз пройти тестирование? Я не нашел ограничений в моделях и сериализаторах

get_all_tests - нет обработчика ситуации, когда нет ни одного теста для прохождения (ошибка 404) - конечно,
маловероятная ситуация...

2024-01-24 12:02 UTC, merged

2024-01-24 12:02 UTC, nikitapatrakov commented
Отличная работа!